packages:
  - 'packages/system'
  - 'packages/angular'
  - 'packages/mcp'
  - 'examples/angular'
  - 'tooling/*'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angflow/system@0.1.2'
